function(render_apply_warnings target_name)
  if(MSVC)
    set(warning_flags /W4 /permissive-)
    if(RENDER_WARNINGS_AS_ERRORS)
      list(APPEND warning_flags /WX)
    endif()
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    set(warning_flags -Wall -Wextra -Wpedantic)
    if(RENDER_WARNINGS_AS_ERRORS)
      list(APPEND warning_flags -Werror)
    endif()
  else()
    set(warning_flags "")
  endif()

  if(warning_flags)
    target_compile_options(${target_name} INTERFACE ${warning_flags})
  endif()
endfunction()
