include(CheckIPOSupported)

function(render_setup_options)
  option(RENDER_BUILD_TOOLS "Build developer tools targets" ON)
  option(RENDER_BUILD_TESTS "Build test targets" ON)
  option(RENDER_WARNINGS_AS_ERRORS "Treat warnings as errors" OFF)
  option(RENDER_ENABLE_SANITIZERS "Enable sanitizer instrumentation when supported" OFF)
  option(RENDER_ENABLE_UNITY_BUILD "Enable unity/jumbo builds" OFF)
  option(RENDER_ENABLE_IPO "Enable link-time optimization/interprocedural optimization" OFF)

  if(NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Debug CACHE STRING "Build type" FORCE)
  endif()

  if(RENDER_ENABLE_IPO)
    check_ipo_supported(RESULT RENDER_IPO_SUPPORTED OUTPUT RENDER_IPO_ERROR)
    if(RENDER_IPO_SUPPORTED)
      set(RENDER_IPO_AVAILABLE TRUE CACHE BOOL "IPO/LTO availability" FORCE)
    else()
      set(RENDER_IPO_AVAILABLE FALSE CACHE BOOL "IPO/LTO availability" FORCE)
      message(WARNING "RENDER_ENABLE_IPO requested but unsupported: ${RENDER_IPO_ERROR}")
    endif()
  else()
    set(RENDER_IPO_AVAILABLE FALSE CACHE BOOL "IPO/LTO availability" FORCE)
  endif()
endfunction()

function(render_apply_project_options target_name)
  target_compile_features(${target_name} INTERFACE cxx_std_20)

  if(RENDER_ENABLE_UNITY_BUILD)
    set_target_properties(${target_name} PROPERTIES UNITY_BUILD ON)
  endif()

  if(RENDER_IPO_AVAILABLE)
    set_target_properties(${target_name} PROPERTIES INTERPROCEDURAL_OPTIMIZATION TRUE)
  endif()

  if(RENDER_ENABLE_SANITIZERS)
    if(MSVC)
      message(STATUS "Sanitizers are currently configured only for Clang/GCC toolchains")
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
      target_compile_options(${target_name} INTERFACE -fsanitize=address,undefined -fno-omit-frame-pointer)
      target_link_options(${target_name} INTERFACE -fsanitize=address,undefined)
    endif()
  endif()
endfunction()
